name: Monitor Wisła Kraków Ticket Sales

on:
  schedule:
    # Uruchamia co minutę
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run ticket monitor
      run: python scripts/monitor_tickets.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Update ticket data $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push
